added failure method

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -28,15 +28,14 @@ jobs:
         distribution: 'temurin'
         cache: maven
     - name: Build with Maven
-      run: mvn clean install
-      continue-on-error: true
+      run: | 
+          mvn clean install
+          if [ $? -ne 0 ]; then
+            exit 1
+          fi
     - name: Check build status
       run: |
-        if [ ${{ job.status }} == 'failure' ]; then
-          echo "Build failed"
-          # Add email alert command here
-        else
-          echo "Build succeeded"
-        fi
+        if failure()
+        run: echo 'Build failed!'
 
    
